### ISSUE TITLE
Not obvious how to run tests

### ISSUE THREAD

**Issue by infinity0** [janestreet/ppx_sexp_conv#12]
There is no "Test" section in `_oasis` so the `make test` target just does nothing.

**Comment by diml** [comment]
In fact, tests are not setup at all. I'm working on re-using our internal build rules for public Jane Street packages. When this is done rules for tests, examples, etc will be magically setup

**Comment by hhugo** [comment]
waitting for https://github.com/janestreet/jbuilder/pull/338

**Comment by aalekseyev** [comment]
I believe most tests are now using deriving_inline, which should work correctly in dune and be run on compilation. 

In time, we make the .mlt tests run as well, but this will have to wait until we're using dune in Jane Street.
In any case, this is a problem not specific to ppx_sexp_conv, so I'm closing this issue for now.
