### ISSUE TITLE
`Sexpable` and Polymorphic variants

### ISSUE THREAD

**Issue by SaswatPadhi** [janestreet/ppx_sexp_conv#19]
I have a `Sexpable` module containing a polymorphic variant type.
The signature I define looks like:
```
module type I =
  sig
    type t = [ `Foo ]

    include Base.Sexpable.S with type t := t
  end
```
And the implementation is:
```
module T : I =
  struct
    type t = [ `Foo ] [@@deriving sexp]
  end
```

But `Sexpable` does not expose `__t_of_sexp__`. So, when I try to use `T` in another module, like:
```
module M = 
  struct
    type tt = T.t [@@deriving sexp_poly]
    type t = [ tt | `Bar ] [@@deriving sexp]
  end
```
This fails because it cannot find `__t_of_sexp__`.
Currently, I am manually exporting `__t_of_sexp__` in my signature `I`, but it would be nice not to have to mess with the signature.

**Comment by SaswatPadhi** [comment]
Also reported it at janestreet/base/#38.
Please close this one if it's not relevant to this repo.

Thanks.

**Comment by diml** [comment]
Why not use `[@@deriving sexp]` in the signature?

**Comment by diml** [comment]
I just saw that the issue was resolved in the other ticket
