### ISSUE TITLE
runtime dependency on base

### ISSUE THREAD

**Issue by hannesm** [janestreet/ppx_sexp_conv#22]
since release v0.11.0, ppx_sexp_conv requires `base` as a runtime dependency.  we in the MirageOS ecosystem are interested in minimal trusted code bases, thus adding `base` is not a good option for us.  (see earlier discussion about sexplib.v0.9.0 from last year at https://www.mail-archive.com/mirageos-devel@lists.xenproject.org/msg02638.html) and some discussion about ppx_sexp_conv at https://github.com/ocaml/opam-repository/issues/11852

now, @diml asked me to open this issue here so that you can track this issue.  here it is.

**Comment by diml** [comment]
I made the change. We are preparing a v0.11.1 release, it will be part of it.

**Comment by hannesm** [comment]
thanks!
