### ISSUE TITLE
Attribute format for sexp_opaque

### ISSUE THREAD

**Issue by belph** [janestreet/ppx_sexp_conv#26]
`sexp_opaque` is useful for omitting certain fields from a serialized output, but leads to some unintended interactions with other ppx libraries. For example, consider the following:

```ocaml
type foo =
  | Bar of int sexp_opaque
[@@deriving sexp, yojson]
```
Leads to the following compilation error:
```
File "_none_", line 1:
Error: Unbound value sexp_opaque_to_yojson
```
Unfortunately, there is no real way to write `sexp_opaque_to_json`. Consider the following (proposed) example instead:
```ocaml
type foo =
  | Bar of int [@sexp_opaque]
[@@deriving sexp, yojson]
```
This would allow things to at least compile. Would you consider adding such a feature?

**Comment by diml** [comment]
Yes, actually we have been thinking about doing this for a while but never took the time to implement it.

**Comment by bcc32** [comment]
We've made this change, and the next opam release should support the `@sexp.opaque` attribute: see the [v0.13-preview.120.28+212 readme](https://github.com/janestreet/ppx_sexp_conv/blob/78c6df6ced265d7d7876809391e0c345709df867/RE_ADME.org#opaque-values)

**Comment by belph** [comment]
🙏 Super! Thanks!

**Comment by shonfeder** [comment]
Looks like this can be closed?

**Comment by bcc32** [comment]
Ah, yes, this is available in OPAM now, so I'm closing this issue.  Thanks for the suggestion!
