### ISSUE TITLE
Redirecting to a polymorphic field?

### ISSUE THREAD

**Issue by cmxog** [janestreet/ppx_sexp_conv#38]
Would it be possible to derive `of_sexp` for:

```ocaml
type 'a r = {
   field: 'a
} [@@deriving of_exp]
```

in such a way that instead of generating a representation of `r` form, it'd just use the `of_exp` representation of `field`?

**Comment by ceastlund** [comment]
I don't think there's a need to add a "deriving" annotation for that. It's easy enough to write by hand:
```
let t_of_sexp a_of_sexp sexp = { field = a_of_sexp sexp }
```
Adding more and more attributes for customizing derived sexps just complicates both the interface and the implementation of ppx_sexp_conv, so for things like this I'd rather not add them.
