### ISSUE TITLE
What should I #require in utop so that it works?

### ISSUE THREAD

**Issue by UnixJunkie** [janestreet/ppx_sexp_conv#4]
#require "i_dont_know_what";;
    type t = Int of int | Float of float [@@deriving sexp];;

Thanks a lot !

**Comment by diml** [comment]
You can do this:

```ocaml
#require "core,ppx_jane";;
open Core.Std;;
type t = Int of int | Float of float [@@deriving sexp];;
```

**Comment by yminsky** [comment]
Or

    #require "ppx_sexp_conv"

if you want just the sexplib converter.  And you can open Sexplib.Std instead of Core.Std for that case as well.

**Comment by UnixJunkie** [comment]
Thanks for the answers. I will try the minimalist way using (open Sexplib.std), and not pull the whole core just for that.

**Comment by UnixJunkie** [comment]
OK, it works in utop:

    #require "ppx_sexp_conv";;
    open Sexplib.Std
    type t = {
      i: int;
      f: float
    } [@@deriving sexp];;

**Comment by UnixJunkie** [comment]
Is it possible to compile such code with an ocamlbuild one-liner and no _tags and myocamlbuild.ml files ?

**Comment by diml** [comment]
This should do: `ocamlbuild -use-ocamlfind -pkg ppx_sexp_conv`

**Comment by UnixJunkie** [comment]
Indeed, thanks!

**Comment by agarwal** [comment]
This issue is resolved. It can be closed.
