### ISSUE TITLE
Doesn't work with `Int64.t`

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/ppx_sexp_conv#5]
``` ocaml
open Sexplib.Std
type xy = { yy : Int64.t } [@@deriving sexp];;
Error: Unbound value Int64.t_of_sexp
```

While it works if `yy: int64`. This isn't such a huge deal but it would be nice to support all the different aliases in pervasives.

**Comment by agarwal** [comment]
Just tried this now, and it seems to work.
