### ISSUE TITLE
GADT support

### ISSUE THREAD

**Issue by ejgallego** [janestreet/ppx_sexp_conv#8]
Dear ppx_sexp_conv devs,

thanks again for this great tool, it would be great if GADTs could be serialized both ways. This:

``` ocaml
type _ obj =
  | OInt :    int obj
  | OStr : string obj
[@@deriving of_sexp]
```

currently results in:

```
Error: This expression has type int obj
       but an expression was expected of type v_x__001_ obj
       Type int is not compatible with type v_x__001_ 
```

Note that `[@@deriving sexp_of]` works fine and it indeed is very useful!

```
```

**Comment by diml** [comment]
Unfortunately it's not possible to write such a function as it would be unsafe. Instead you need to wrap the type into a GADT to introduce the existential:

```ocaml
type packed_obj = Obj : _ obj -> packed_obj
```

Currently there is no special support in findlib for types that are wrapped in such a way. What we usually do is define a helper type:

```ocaml
module For_sexp = struct
  type t = OInt | OStr [@@deriving of_sexp]
end

type _ t = OInt : int t | OStr : string t

type packed = T : _ t -> packed

let packed_of_sexp sexp =
  match For_sexp.t_of_sexp with
  | OInt -> T OInt
  | OStr -> T OStr
```

**Comment by ejgallego** [comment]
Thank you very much for the reply @diml

**Comment by aalekseyev** [comment]
I'm closing this issue because the specific question got answered. The general support of GADTs is a complicated topic and definitely not fully explored. Any proposals for how to support GADTs are welcome in separate issues.
