### ISSUE TITLE
Support inline records of OCaml 4.03?

### ISSUE THREAD

**Issue by liweijian** [janestreet/ppx_sexp_conv#9]
I tried to test the example from this [post](https://blogs.janestreet.com/ocaml-4-03-everything-else/):

``` ocaml
utop #
type shape =
  | Circle of { center_x: float;
                center_y: float;
                radius: float;
              }
  | Rect of { x_lo: float;
              y_lo: float;
              x_hi: float;
              y_hi: float;
            }
;;
type shape =
    Circle of { center_x : float; center_y : float; radius : float; }
  | Rect of { x_lo : float; y_lo : float; x_hi : float; y_hi : float; }
```

It works as expected, but there's error when I add `[@@deriving sexp]`:

``` ocaml
utop #
type shape =
  | Circle of { center_x: float;
                center_y: float;
                radius: float;
              }
  | Rect of { x_lo: float;
              y_lo: float;
              x_hi: float;
              y_hi: float;
            }
[@@deriving sexp]
;;
Error: Error while running external preprocessor
Command line: /Users/liweijian/.opam/4.03.0/lib/ppx_deriving/./ppx_deriving '/var/folders/6m/g2c97rl9517201ffjyspkxlw0000gn/T/camlppxa5e248' '/var/folders/6m/g2c97rl9517201ffjyspkxlw0000gn/T/camlppxc2357d'
```

**Comment by trefis** [comment]
Inline records are indeed not supported at the moment. 

The 4.03-compatible version of our libraries and tools was meant as "a preview"/"an alpha release": we released it during the beta of the compiler so people could start trying their codebase with the new compiler. In particular the main interest was to work with existing (4.02) code, supporting new features of the language was not required.

We are going to switch to 4.03 internally very soon, at which point we will release new versions of our libraries which will work with 4.03 and should support these new features.

**Comment by smolkaj** [comment]
+1
Support for inline records would be very much appreciated :)

**Comment by diml** [comment]
It's almost done internally. We are just discussing whether the sexp for `A of { x : int; y : int }` should be `(A (x 1) (y 2))` or `(A ((x 1) (y 2)))`

**Comment by smolkaj** [comment]
Any updates on this?

**Comment by yminsky** [comment]
It's already fixed in our bleeding-edge release, which you can access here:

**Comment by smolkaj** [comment]
Great, thanks!

**Comment by liweijian** [comment]
I just found that inline records has been supported

```ocaml
type shape =
  | Circle of { center_x: float;
                center_y: float;
                radius: float;
              }
  | Rect of { x_lo: float;
              y_lo: float;
              x_hi: float;
              y_hi: float;
            }
[@@deriving sexp]
;;
type shape =
    Circle of { center_x : float; center_y : float; radius : float; }
  | Rect of { x_lo : float; y_lo : float; x_hi : float; y_hi : float; }
```
